### PR TITLE
Message object in reaction events

### PR DESCRIPTION
**Pull request by Foxite**
Passes the message object to users for OnReactionAdded and OnReactionRemoved events.

Also adds a testbot feature to demonstrate this; it will now mirror every reaction that gets added or removed.

### CODE REVIEW

**Comment by xXBuilderBXx** [comment]
Instead of downloading each message on reaction we should make the message object into a Downloadable message class that way it's optional and users can run a GetMessageAsync() to get the original message

**Comment by Foxite** [comment]
You mean make it like this:

`Downloadable<Message>`

and then

````csharp
client.OnReactionAdded += async (..., messageDownload) => {
    var message = await messageDownload.DownloadAsync();
    // ...
}
```

That sounds like a good idea to me.

**Comment by Foxite** [comment]
Should the same thing be done for the ServerMember?

**Comment by xXBuilderBXx** [comment]
We can include the message id along with a GetMessageAsync()
Server member could work too and pull from cache first.

**Comment by Foxite** [comment]
Downloadable now includes the id of the object to be downloaded.

**Comment by xXBuilderBXx** [comment]
Nice will check this out in a few hours currently working atm :)

**Comment by xXBuilderBXx** [comment]
Sorry for the wait will begin merging this into the lib, nice to know a fellow developer that understands C# well :D

**Pull request merged**
